# Generated by Django 4.2.7 on 2025-11-23 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Código do ativo (ex: PETR4, VALE3)', max_length=20, verbose_name='Ticker')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('setor', models.CharField(blank=True, help_text='Setor da empresa (ex: Petróleo, Mineração)', max_length=100, null=True, verbose_name='Setor')),
                ('pais', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['ticker'],
                'unique_together': {('usuario', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='MetaRenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para esta meta (ex: Independência Financeira)', max_length=200, verbose_name='Nome da Meta')),
                ('renda_mensal_desejada', models.DecimalField(decimal_places=2, help_text='Valor da renda mensal que deseja receber em dividendos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Renda Mensal Desejada (R$)')),
                ('anos_para_atingir', models.PositiveIntegerField(help_text='Quantos anos você tem para atingir esta meta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anos para Atingir')),
                ('inflacao_media_anual', models.DecimalField(decimal_places=2, default=4.5, help_text='Percentual de inflação média anual esperada', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Inflação Média Anual (%)')),
                ('percentual_reinvestimento', models.DecimalField(decimal_places=2, default=0, help_text='Percentual dos dividendos que serão reinvestidos', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de Reinvestimento (%)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_renda', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta de Renda',
                'verbose_name_plural': 'Metas de Renda',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_alvo', models.DecimalField(decimal_places=2, help_text='Patrimônio necessário para atingir a meta', max_digits=15, verbose_name='Patrimônio Alvo (R$)')),
                ('aporte_mensal', models.DecimalField(decimal_places=2, help_text='Valor que precisa investir mensalmente', max_digits=12, verbose_name='Aporte Mensal Necessário (R$)')),
                ('yield_medio_usado', models.DecimalField(blank=True, decimal_places=2, help_text='Yield médio utilizado no cálculo', max_digits=5, null=True, verbose_name='Yield Médio Usado (%)')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('meta_renda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='planner.metarenda', verbose_name='Meta de Renda')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('valor_por_acao', models.DecimalField(decimal_places=4, help_text='Valor do dividendo pago por ação', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor por Ação (R$)')),
                ('fonte', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10, verbose_name='Fonte')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_dividendos', to='planner.ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Histórico de Dividendo',
                'verbose_name_plural': 'Históricos de Dividendos',
                'ordering': ['-data_pagamento', '-data_criacao'],
            },
        ),
    ]
